### ISSUE TITLE
task01似乎有些错误

### ISSUE THREAD

**Issue by San-greal** [milLearningGroup/autumn_2017#42]
task01的第三个代码框input[3]似乎是有问题的，缩进和命名好像有些错误（seed和return),能不能看一下？

**Comment by XIWuXueWei** [comment]
或许input[3]里的代码应该属于input[6]的generate_train_and_test()方法里

**Comment by San-greal** [comment]
train_and_test用 train_test_split就行了

**Comment by AcceptedDoge** [comment]
@XIWuXueWei 的解释是正确的，这似乎是上一期作业文件遗留下来的问题，已经去掉了对应的代码部分。

另外在**编程练习 2: 数据分割与重排**部分的要求写得很明确了，对可能需要用到的函数也进行了补充，因此不建议直接一行代码调包完成你的工作（即使你可能对于skl很熟悉），而是根据问题表述去写基础的实现步骤。**这一部分的设置是为了检验你对Python和Numpy的熟悉程度。**

请大家及时地进行`git pull`以及`git merge`操作，以获得最新版本的作业文件。
