### ISSUE TITLE
给我一点提示：用jupyter notbook 来写一个自定义模板文件并导入？

### ISSUE THREAD

**Issue by Murray0575** [milLearningGroup/autumn_2017#65]
1. 这个ISSUE是根据我在用jupyter notebook写了一个模板后，我想用另一的.ipynb文件调用这个模板发现的。  
2. 我遇到的主要问题为：  
我的工作路径如图，相关文件已经在一个目录下：
![3](https://user-images.githubusercontent.com/28613250/31949910-037d3fae-b90d-11e7-959f-bf2cb0fa3233.PNG)
但jupyter notebook 好像没办法写.py文件，因为直接把.ipynb后缀改为.py,会造成读写错误
![1](https://user-images.githubusercontent.com/28613250/31949446-ebcc4f0e-b90b-11e7-849b-afab95c0813f.PNG)
我用IDEL写了同样的一份，保存为.py文件就可以导入了
![2](https://user-images.githubusercontent.com/28613250/31949498-0d1440e0-b90c-11e7-849f-4487dfcce14f.PNG)
问：我是否可以用过jupyter notbook 来写一个自定义文件并导入？
3. 我已经进行了如下尝试:
https://stackoverflow.com/questions/9383014/cant-import-my-own-modules-in-python
http://www.jianshu.com/p/bb0eab1b2535
4. 我的操作系统版本为：win10
5. 我的Python版本为：Python 2.7

**Comment by AcceptedDoge** [comment]
你的问题我已经了解了，不知道你是否进行过这样的尝试：
**在运行你的 Jupyter Notebook 时，在左上角的菜单栏找到**
```
File—>Download as—>python(.py)
```
**就能够导出为 python 格式。**

也就是说， Jupyter Notebook 是支持将 你写好的 `.ipynb` 后缀文件直接导出为 `.py` 后缀文件的，
同样地，`.ipynb` 后缀文件 还可以导出为`PDF`，`html` 等支持的其它格式。

如果你在 Notebook 写好了你的代码，并且想导出为 `.py` 后缀文件作为一个可调用的包，可以参考一下上面提到的操作。如果你用文本编辑器打开 `.ipynb` 后缀文件，你会发现它的结构其实很简单。但是由于要区分Cell中markdown格式，所以直接修改后缀是行不通的。（就好像你把一个doc文件修改为txt格式打开会乱码。）

希望能够帮助到你~

**Comment by Murray0575** [comment]
问题已解决，谢谢
