### ISSUE TITLE
是否有同学愿意参加斯坦福大学CS229机器学习笔记的整理工作？

### ISSUE THREAD

**Issue by AcceptedDoge** [milLearningGroup/autumn_2017#66]
- Stanford CS229课程主页：http://cs229.stanford.edu/
- 已经有人对英文笔记进行了汉化：https://github.com/Kivy-CN/Stanford-CS-229-CN
- 我们的预备存储库：https://github.com/milLearningGroup/Stanford-CS229-CN

## 需要态度认真，严谨的小伙伴
说句实在话，这会有点耗费你的时间，但是实际上大部分的汉化工作已经完成了。我们要做的就是进一步的优化笔记的质量，具体来说我们的工作流程就是：
1. 获得英文的文档和中文的文档；
2. 参考中英文文档使用 Markdown 语法对其内容和语序进行改进；
3. 把数学公式和图片链接合理化，使之更加具有逻辑性。

可见对于英文的要求并不高，已经有中文初稿了！

### 你能够获得什么？
1. 理解这个笔记会让你的机器学习理论和概念变得十分扎实；
2. 你等同于拥有了一次参加GitHub开源项目的经验；
3. 你需要学习LaTeX或是Mathjax语法，对于毕业写论文会有帮助。

### 其它想法
笔记完成后，我会给吴恩达（Andrew Ng）教授发邮件申请中文翻译正式的授权。
如果参与人数过少，这个计划将会被暂时的搁置。

任何对此项目有想法的同学，欢迎在这个Issue下回复。
我推荐 @vateye 作为项目负责人，他的数学功底十分不错。

**Comment by San-greal** [comment]
好啊，ojbk

**Comment by BoyaYang** [comment]
加我一个~

**Comment by Galileo-Bill** [comment]
想一起好好学习LeTex = =

**Comment by AcceptedDoge** [comment]
@BoyaYang 请查看邮件接受一个入组邀请

**Comment by Murray0575** [comment]
算我一个吧

**Comment by minygd** [comment]
+1

**Comment by Hezzhm** [comment]
加我一个凹~

**Comment by AcceptedDoge** [comment]
@Hezzhm  欢迎欢迎，访问这里：https://github.com/milLearningGroup/Stanford-CS229-CN/blob/master/CONTRIBUTING.md
