### ISSUE TITLE
名单疑问

### ISSUE THREAD

**Issue by Faith-Uchiha** [milLearningGroup/autumn_2017#79]
组长不好意思，名单确认晚了。 之前我报名已经填了github账号，为何在[名单](https://544273239.docs.qq.com/1FGZ74TMB3W)   上只看到自己的名字。

p.s:罗兰学长开会时说道应该使用Python3.5，但我之前听说3还未普及且与2.7有较大差异，
所以安装的是Python2.7。请问需要重新安装吗？

不知道这样的issue会不会恼人。。

**Comment by minygd** [comment]
Anaconda 可以划分不同的环境（你可以理解为一个商品房有几个不同的房间，互不干扰），完全可以在Anaconda2.7下创建一个python3.5的开发环境，与原环境互不影响。

**Comment by Faith-Uchiha** [comment]
谢谢@minygd，之前发Issue的时候没往后看Anaconda的创建环境部分。
